In [4]:
import flor

In [2]:
page_text = flor.dataframe("page_text")
page_text = page_text[["projid", "tstamp", "filename", "paper", "paper_value", "page", "page_text"]]
page_text

,projid,tstamp,filename,paper,paper_value,page,page_text
0,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,1,Effects of Sharing Physiological States of Pla...
1,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,2,This work is novel because it is one of the ﬁr...
2,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,3,"collaboration [29]. Finally, a recent work by ..."
3,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,4,Figure 2. In this user study we used two diffe...
4,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,5,Figure 3. The user study setup. Both player an...
5,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,6,Male\nFemale\nCondition\nCount\nAge\nCount\nAg...
6,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,7,Game\nZombie\nButterfly\nRealized Emotional St...
7,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,8,Game\nZombie\nButterfly\nScore\n4 0\n3 0\n2 0\...
8,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,9,Figure 7. Observers looked differently in the ...
9,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,10,"Finally, as mentioned in the earlier section, ..."
10,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,11,"REFERENCES\n1. A. Aron, Aron E. N., and D. Smo..."
11,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,1,known_pdfs/p4045.pdf,12,Video-mediated Collaboration. In Proceedings o...
12,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,1,1\nSCientifiC REPORTS | 7:45125 | DOI: 10.1038...
13,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,2,www.nature.com/scientificreports/\n2\nSCientif...
14,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,3,www.nature.com/scientificreports/\n3\nSCientif...
15,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,4,www.nature.com/scientificreports/\n4\nSCientif...
16,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,5,www.nature.com/scientificreports/\n5\nSCientif...
17,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,6,www.nature.com/scientificreports/\n6\nSCientif...
18,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,7,www.nature.com/scientificreports/\n7\nSCientif...
19,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,8,www.nature.com/scientificreports/\n8\nSCientif...
20,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,9,www.nature.com/scientificreports/\n9\nSCientif...
21,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,10,www.nature.com/scientificreports/\n10\nSCienti...
22,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,11,www.nature.com/scientificreports/\n11\nSCienti...
23,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,12,www.nature.com/scientificreports/\n12\nSCienti...
24,research_reviewer_main,2024-09-09 10:27:35,parse_text.py,2,known_pdfs/srep45125.pdf,13,www.nature.com/scientificreports/\n13\nSCienti...

In [6]:
synthetic_papers = flor.utils.latest(flor.dataframe("title", "author", "references"))
synthetic_papers = synthetic_papers[["projid", "tstamp", "filename", "paper", "title", "author", "references"]]
synthetic_papers

,projid,tstamp,filename,paper,title,author,references
0,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,1,Application of Robotics,Timothy Williams,"['Grayson Perez et al., Analysis of Robotics, ..."
1,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,2,Review of Robotics,Susan Brown,"['Anthony Moore et al., Testing of Environment..."
2,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,3,Testing of Quantum Mechanics,Robert Scott,"['Gabriel Lopez et al., Investigation of Softw..."
3,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,4,Application of Environmental Science,Mary Adams,"['Sandra Johnson et al., Research of Environme..."
4,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,5,Review of Global Warming,Ethan Nelson,"['John Anderson et al., Research of Public Hea..."
5,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,6,Exploration of Software Engineering,Gabriel Thompson,"['Margaret Perez et al., Observation of Roboti..."
6,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,7,Review of Artificial Intelligence,Kenneth Harris,"['Matthew Lewis et al., Measurement of Robotic..."
7,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,8,Measurement of Neuroscience,Ethan Campbell,"['Michael Gonzalez et al., Analysis of Neurosc..."
8,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,9,Observation of Quantum Mechanics,Barbara Rodriguez,"['Thomas Lopez et al., Investigation of Bioche..."
9,research_reviewer_main,2024-09-09 10:56:24,synthetic.py,10,Examination of Neuroscience,David Perez,"['Sandra Rodriguez et al., Exploration of Robo..."